let countryList = [
    { "name": "United States", "code": "1", "codeName": "USA" },
    { "name": "Afghanistan", "code": "93", "codeName": "AFG" },
    { "name": "Albania", "code": "355", "codeName": "ALB" },
    { "name": "Algeria", "code": "213", "codeName": "DZA" },
    { "name": "American Samoa", "code": "1684", "codeName": "ASM" },
    { "name": "Andorra", "code": "376", "codeName": "AND" },
    { "name": "Angola", "code": "244", "codeName": "AGO" },
    { "name": "Anguilla", "code": "1264", "codeName": "AIA" },
    { "name": "Antarctica", "code": "672", "codeName": "ATA" },
    { "name": "Antigua and Barbuda", "code": "1268", "codeName": "ATG" },
    { "name": "Argentina", "code": "54", "codeName": "ARG" },
    { "name": "Armenia", "code": "374", "codeName": "ARM" },
    { "name": "Aruba", "code": "297", "codeName": "ABW" },
    { "name": "Ascension Island", "code": "247", "codeName": "ASC" },
    { "name": "Australia", "code": "61", "codeName": "AUS" },
    { "name": "Austria", "code": "43", "codeName": "AUT" },
    { "name": "Azerbaijan", "code": "994", "codeName": "AZE" },
    { "name": "Bahamas", "code": "1242", "codeName": "BHS" },
    { "name": "Bahrain", "code": "973", "codeName": "BHR" },
    { "name": "Bangladesh", "code": "880", "codeName": "BGD" },
    { "name": "Barbados", "code": "1246", "codeName": "BRB" },
    { "name": "Belarus", "code": "375", "codeName": "BLR" },
    { "name": "Belgium", "code": "32", "codeName": "BEL" },
    { "name": "Belize", "code": "501", "codeName": "BLZ" },
    { "name": "Benin", "code": "229", "codeName": "BEN" },
    { "name": "Bermuda", "code": "1441", "codeName": "BMU" },
    { "name": "Bhutan", "code": "975", "codeName": "BTN" },
    { "name": "Bolivia", "code": "591", "codeName": "BOL" },
    { "name": "Bosnia and Herzegovina", "code": "387", "codeName": "BIH" },
    { "name": "Botswana", "code": "267", "codeName": "BWA" },
    { "name": "Brazil", "code": "55", "codeName": "BRA" },
    { "name": "British Virgin Islands", "code": "1284", "codeName": "VGB" },
    { "name": "Brunei", "code": "673", "codeName": "BRN" },
    { "name": "Bulgaria", "code": "359", "codeName": "BGR" },
    { "name": "Burkina Faso", "code": "226", "codeName": "BFA" },
    { "name": "Burma (Myanmar)", "code": "95", "codeName": "MMR" },
    { "name": "Burundi", "code": "257", "codeName": "BDI" },
    { "name": "Cambodia", "code": "855", "codeName": "KHM" },
    { "name": "Cameroon", "code": "237", "codeName": "CMR" },
    { "name": "Canada", "code": "1", "codeName": "CAN" },
    { "name": "Cape Verde", "code": "238", "codeName": "CPV" },
    { "name": "Cayman Islands", "code": "1345", "codeName": "CYM" },
    { "name": "Central African Republic", "code": "236", "codeName": "CAF" },
    { "name": "Chad", "code": "235", "codeName": "TCD" },
    { "name": "Chile", "code": "56", "codeName": "CHL" },
    { "name": "China", "code": "86", "codeName": "CHN" },
    { "name": "Christmas Island", "code": "61", "codeName": "CXR" },
    { "name": "Cocos (Keeling) Islands", "code": "61", "codeName": "CCK" },
    { "name": "Colombia", "code": "57", "codeName": "COL" },
    { "name": "Comoros", "code": "269", "codeName": "COM" },
    { "name": "Congo", "code": "242", "codeName": "COG" },
    { "name": "Cook Islands", "code": "682", "codeName": "COK" },
    { "name": "Costa Rica", "code": "506", "codeName": "CRC" },
    { "name": "Croatia", "code": "385", "codeName": "HRV" },
    { "name": "Cuba", "code": "53", "codeName": "CUB" },
    { "name": "Cyprus", "code": "357", "codeName": "CYP" },
    { "name": "Czech Republic", "code": "420", "codeName": "CZE" },
    { "name": "Democratic Republic of the Congo", "code": "243", "codeName": "COD" },
    { "name": "Denmark", "code": "45", "codeName": "DNK" },
    { "name": "Diego Garcia", "code": "246", "codeName": "DGA" },
    { "name": "Djibouti", "code": "253", "codeName": "DJI" },
    { "name": "Dominica", "code": "1767", "codeName": "DMA" },
    { "name": "Dominican Republic", "code": "1809", "codeName": "DOM" },
    { "name": "Ecuador", "code": "593", "codeName": "ECU" },
    { "name": "Egypt", "code": "20", "codeName": "EGY" },
    { "name": "El Salvador", "code": "503", "codeName": "SLV" },
    { "name": "Equatorial Guinea", "code": "240", "codeName": "GNQ" },
    { "name": "Eritrea", "code": "291", "codeName": "ERI" },
    { "name": "Estonia", "code": "372", "codeName": "EST" },
    { "name": "Ethiopia", "code": "251", "codeName": "ETH" },
    { "name": "Falkland Islands", "code": "500", "codeName": "FLK" },
    { "name": "Faroe Islands", "code": "298", "codeName": "FRO" },
    { "name": "Fiji", "code": "679", "codeName": "FJI" },
    { "name": "Finland", "code": "358", "codeName": "FIN" },
    { "name": "France", "code": "33", "codeName": "FRA" },
    { "name": "French Guiana", "code": "594", "codeName": "GUF" },
    { "name": "French Polynesia", "code": "689", "codeName": "PYF" },
    { "name": "Gabon", "code": "241", "codeName": "GAB" },
    { "name": "Gambia", "code": "220", "codeName": "GMB" },
    { "name": "Georgia", "code": "995", "codeName": "GEO" },
    { "name": "Germany", "code": "49", "codeName": "DEU" },
    { "name": "Ghana", "code": "233", "codeName": "GHA" },
    { "name": "Gibraltar", "code": "350", "codeName": "GIB" },
    { "name": "Greece", "code": "30", "codeName": "GRC" },
    { "name": "Greenland", "code": "299", "codeName": "GRL" },
    { "name": "Grenada", "code": "1473", "codeName": "GRD" },
    { "name": "Guadeloupe", "code": "590", "codeName": "GLP" },
    { "name": "Guam", "code": "1671", "codeName": "GUM" },
    { "name": "Guatemala", "code": "502", "codeName": "GTM" },
    { "name": "Guinea", "code": "224", "codeName": "GIN" },
    { "name": "Guinea-Bissau", "code": "245", "codeName": "GNB" },
    { "name": "Guyana", "code": "592", "codeName": "GUY" },
    { "name": "Haiti", "code": "509", "codeName": "HTI" },
    { "name": "Holy See (Vatican City)", "code": "39", "codeName": "VAT" },
    { "name": "Honduras", "code": "504", "codeName": "HND" },
    { "name": "Hong Kong", "code": "852", "codeName": "HKG" },
    { "name": "Hungary", "code": "36", "codeName": "HUN" },
    { "name": "Iceland", "code": "354", "codeName": "IS" },
    { "name": "India", "code": "91", "codeName": "IND" },
    { "name": "Indonesia", "code": "62", "codeName": "IDN" },
    { "name": "Iran", "code": "98", "codeName": "IRN" },
    { "name": "Iraq", "code": "964", "codeName": "IRQ" },
    { "name": "Ireland", "code": "353", "codeName": "IRL" },
    { "name": "Isle of Man", "code": "44", "codeName": "IMN" },
    { "name": "Israel", "code": "972", "codeName": "ISR" },
    { "name": "Italy", "code": "39", "codeName": "ITA" },
    { "name": "Ivory Coast (Côte d'Ivoire)", "code": "225", "codeName": "CIV" },
    { "name": "Jamaica", "code": "1876", "codeName": "JAM" },
    { "name": "Japan", "code": "81", "codeName": "JPN" },
    { "name": "Jersey", "code": "44", "codeName": "JEY" },
    { "name": "Jordan", "code": "962", "codeName": "JOR" },
    { "name": "Kazakhstan", "code": "7", "codeName": "KAZ" },
    { "name": "Kenya", "code": "254", "codeName": "KEN" },
    { "name": "Kiribati", "code": "686", "codeName": "KIR" },
    { "name": "Kuwait", "code": "965", "codeName": "KWT" },
    { "name": "Kyrgyzstan", "code": "996", "codeName": "KGZ" },
    { "name": "Laos", "code": "856", "codeName": "LAO" },
    { "name": "Latvia", "code": "371", "codeName": "LVA" },
    { "name": "Lebanon", "code": "961", "codeName": "LBN" },
    { "name": "Lesotho", "code": "266", "codeName": "LSO" },
    { "name": "Liberia", "code": "231", "codeName": "LBR" },
    { "name": "Libya", "code": "218", "codeName": "LBY" },
    { "name": "Liechtenstein", "code": "423", "codeName": "LIE" },
    { "name": "Lithuania", "code": "370", "codeName": "LTU" },
    { "name": "Luxembourg", "code": "352", "codeName": "LUX" },
    { "name": "Macau", "code": "853", "codeName": "MAC" },
    { "name": "Macedonia", "code": "389", "codeName": "MKD" },
    { "name": "Madagascar", "code": "261", "codeName": "MDG" },
    { "name": "Malawi", "code": "265", "codeName": "MWI" },
    { "name": "Malaysia", "code": "60", "codeName": "MYS" },
    { "name": "Maldives", "code": "960", "codeName": "MDV" },
    { "name": "Mali", "code": "223", "codeName": "MLI" },
    { "name": "Malta", "code": "356", "codeName": "MLT" },
    { "name": "Marshall Islands", "code": "692", "codeName": "MHL" },
    { "name": "Martinique", "code": "596", "codeName": "MTQ" },
    { "name": "Mauritania", "code": "222", "codeName": "MRT" },
    { "name": "Mauritius", "code": "230", "codeName": "MUS" },
    { "name": "Mayotte", "code": "262", "codeName": "MYT" },
    { "name": "Mexico", "code": "52", "codeName": "MEX" },
    { "name": "Micronesia", "code": "691", "codeName": "FSM" },
    { "name": "Moldova", "code": "373", "codeName": "MDA" },
    { "name": "Monaco", "code": "377", "codeName": "MCO" },
    { "name": "Mongolia", "code": "976", "codeName": "MNG" },
    { "name": "Montenegro", "code": "382", "codeName": "MNE" },
    { "name": "Montserrat", "code": "1664", "codeName": "MSR" },
    { "name": "Morocco", "code": "212", "codeName": "MAR" },
    { "name": "Mozambique", "code": "258", "codeName": "MOZ" },
    { "name": "Namibia", "code": "264", "codeName": "NAM" },
    { "name": "Nauru", "code": "674", "codeName": "NRU" },
    { "name": "Nepal", "code": "977", "codeName": "NPL" },
    { "name": "Netherlands", "code": "31", "codeName": "NLD" },
    { "name": "Netherlands Antilles", "code": "599", "codeName": "ANT" },
    { "name": "New Caledonia", "code": "687", "codeName": "NCL" },
    { "name": "New Zealand", "code": "64", "codeName": "NZL" },
    { "name": "Nicaragua", "code": "505", "codeName": "NIC" },
    { "name": "Niger", "code": "227", "codeName": "NER" },
    { "name": "Nigeria", "code": "234", "codeName": "NGA" },
    { "name": "Niue", "code": "683", "codeName": "NIU" },
    { "name": "Norfolk Island", "code": "672", "codeName": "NFK" },
    { "name": "North Korea", "code": "850", "codeName": "PRK" },
    { "name": "Northern Mariana Islands", "code": "1670", "codeName": "MNP" },
    { "name": "Norway", "code": "47", "codeName": "NOR" },
    { "name": "Oman", "code": "968", "codeName": "OMN" },
    { "name": "Pakistan", "code": "92", "codeName": "PAK" },
    { "name": "Palau", "code": "680", "codeName": "PLW" },
    { "name": "Palestine", "code": "970", "codeName": "PSE" },
    { "name": "Panama", "code": "507", "codeName": "PAN" },
    { "name": "Papua New Guinea", "code": "675", "codeName": "PNG" },
    { "name": "Paraguay", "code": "595", "codeName": "PRY" },
    { "name": "Peru", "code": "51", "codeName": "PER" },
    { "name": "Philippines", "code": "63", "codeName": "PHL" },
    { "name": "Pitcairn Islands", "code": "870", "codeName": "PCN" },
    { "name": "Poland", "code": "48", "codeName": "POL" },
    { "name": "Portugal", "code": "351", "codeName": "PRT" },
    { "name": "Puerto Rico", "code": "1787", "codeName": "PRI" },
    { "name": "Qatar", "code": "974", "codeName": "QAT" },
    { "name": "Republic of the Congo", "code": "242", "codeName": "COG" },
    { "name": "Reunion Island", "code": "262", "codeName": "REU" },
    { "name": "Romania", "code": "40", "codeName": "ROU" },
    { "name": "Russia", "code": "7", "codeName": "RUS" },
    { "name": "Rwanda", "code": "250", "codeName": "RWA" },
    { "name": "Saint Barthelemy", "code": "590", "codeName": "BLM" },
    { "name": "Saint Helena", "code": "290", "codeName": "SHN" },
    { "name": "Saint Kitts and Nevis", "code": "1869", "codeName": "KNA" },
    { "name": "Saint Lucia", "code": "1758", "codeName": "LCA" },
    { "name": "Saint Martin", "code": "590", "codeName": "MAF" },
    { "name": "Saint Pierre and Miquelon", "code": "508", "codeName": "SPM" },
    { "name": "Saint Vincent and the Grenadines", "code": "1784", "codeName": "VCT" },
    { "name": "Samoa", "code": "685", "codeName": "WSM" },
    { "name": "San Marino", "code": "378", "codeName": "SMR" },
    { "name": "Sao Tome and Principe", "code": "239", "codeName": "STP" },
    { "name": "Saudi Arabia", "code": "966", "codeName": "SAU" },
    { "name": "Senegal", "code": "221", "codeName": "SEN" },
    { "name": "Serbia", "code": "381", "codeName": "SRB" },
    { "name": "Seychelles", "code": "248", "codeName": "SYC" },
    { "name": "Sierra Leone", "code": "232", "codeName": "SLE" },
    { "name": "Singapore", "code": "65", "codeName": "SGP" },
    { "name": "Sint Maarten", "code": "1721", "codeName": "SXM" },
    { "name": "Slovakia", "code": "421", "codeName": "SVK" },
    { "name": "Slovenia", "code": "386", "codeName": "SVN" },
    { "name": "Solomon Islands", "code": "677", "codeName": "SLB" },
    { "name": "Somalia", "code": "252", "codeName": "SOM" },
    { "name": "South Africa", "code": "27", "codeName": "ZAF" },
    { "name": "South Korea", "code": "82", "codeName": "KOR" },
    { "name": "South Sudan", "code": "211", "codeName": "SSD" },
    { "name": "Spain", "code": "34", "codeName": "ESP" },
    { "name": "Sri Lanka", "code": "94", "codeName": "LKA" },
    { "name": "Sudan", "code": "249", "codeName": "SDN" },
    { "name": "Suriname", "code": "597", "codeName": "SUR" },
    { "name": "Svalbard", "code": "47", "codeName": "SJM" },
    { "name": "Swaziland", "code": "268", "codeName": "SWZ" },
    { "name": "Sweden", "code": "46", "codeName": "SWE" },
    { "name": "Switzerland", "code": "41", "codeName": "CHE" },
    { "name": "Syria", "code": "963", "codeName": "SYR" },
    { "name": "Taiwan", "code": "886", "codeName": "TWN" },
    { "name": "Tajikistan", "code": "992", "codeName": "TJK" },
    { "name": "Tanzania", "code": "255", "codeName": "TZA" },
    { "name": "Thailand", "code": "66", "codeName": "THA" },
    { "name": "Timor-Leste (East Timor)", "code": "670", "codeName": "TLS" },
    { "name": "Togo", "code": "228", "codeName": "TGO" },
    { "name": "Tokelau", "code": "690", "codeName": "TKL" },
    { "name": "Tonga Islands", "code": "676", "codeName": "TON" },
    { "name": "Trinidad and Tobago", "code": "1868", "codeName": "TTO" },
    { "name": "Tunisia", "code": "216", "codeName": "TUN" },
    { "name": "Turkey", "code": "90", "codeName": "TUR" },
    { "name": "Turkmenistan", "code": "993", "codeName": "TKM" },
    { "name": "Turks and Caicos Islands", "code": "1649", "codeName": "TCA" },
    { "name": "Tuvalu", "code": "688", "codeName": "TUV" },
    { "name": "Uganda", "code": "256", "codeName": "UGA" },
    { "name": "Ukraine", "code": "380", "codeName": "UKR" },
    { "name": "United Arab Emirates", "code": "971", "codeName": "ARE" },
    { "name": "United Kingdom", "code": "44", "codeName": "GBR" },
    { "name": "Uruguay", "code": "598", "codeName": "URY" },
    { "name": "US Virgin Islands", "code": "1340", "codeName": "VIR" },
    { "name": "Uzbekistan", "code": "998", "codeName": "UZB" },
    { "name": "Vanuatu", "code": "678", "codeName": "VUT" },
    { "name": "Venezuela", "code": "58", "codeName": "VEN" },
    { "name": "Vietnam", "code": "84", "codeName": "VNM" },
    { "name": "Wallis and Futuna", "code": "681", "codeName": "WLF" },
    { "name": "Western Sahara", "code": "212", "codeName": "ESH" },
    { "name": "Yemen", "code": "967", "codeName": "YEM" },
    { "name": "Zambia", "code": "260", "codeName": "ZMB" },
    { "name": "Zimbabwe", "code": "263", "codeName": "ZWE" }
  
  ]
  export default countryList;